### ISSUE TITLE
Getting constant new device email reports after update to 23.10.2

### ISSUE THREAD

**Issue by rama31244** [jokob-sk/Pi.Alert#474]
I'm running pialert as a docker container on my unraid server and after the recent update to 23.10.2, I get about 5 to 10 'new device' email reports a day notifying me about the same devices I've always had. I tried updating the crom schedule of the ARPscan to match the internet scan but this hasn't resolved the problem. Anyone know what might be going on?

**Comment by jokob-sk** [comment]
Looks like duplicate: https://github.com/jokob-sk/Pi.Alert/issues/462

**Comment by tamimology** [comment]
I am getting constant notifications for my NBN device being connected/disconnected. I stopped the container last night until it is resolved :(

![WhatsApp Image 2023-10-08 at 11 23 59](https://github.com/jokob-sk/Pi.Alert/assets/90429593/3c8264b4-6b35-4b4c-9633-d7189fd663a6)

**Comment by jokob-sk** [comment]
@tamimology please read #462

**Comment by rama31244** [comment]
Hi, here are the requested details
Example of the report: Attached below
![Screenshot 2023-10-08 at 4 47 01 pm](https://github.com/jokob-sk/Pi.Alert/assets/85214694/04bf92ef-962f-4278-bf19-be820835be79)

Output of the PLugin: I'm not sure which plugin is creating the report but i assume ARPscan

![Screenshot 2023-10-08 at 4 51 58 pm(1)](https://github.com/jokob-sk/Pi.Alert/assets/85214694/51b9674f-2609-4147-8e1a-611f6dd4352b)

    pialert.log output in debug mode: Sorry, i can't find the pialert.log

**Comment by jokob-sk** [comment]
@rama31244 please post the pialert.log file from the Maintenance, Logs section.

Also, what reports and notifications have you enabled?

**Comment by tamimology** [comment]
> @tamimology please read #462

This worked for me
Thanks

**Comment by rama31244** [comment]
The log file is over 30mb, any advice on how I can include it? As for notifications, I have it set to notify on new and report on new (on pholus and arpscan)

**Comment by rama31244** [comment]
I worked it out, just purged it and now have a smaller file
[pialert(1).log](https://github.com/jokob-sk/Pi.Alert/files/12842405/pialert.1.log)

**Comment by jokob-sk** [comment]
Hi @rama31244 

I checked your log and there are no alerts sent in the time frame of the logs you shared. There are always 0 new devices:

```
08:11:13 [Save Devices] Saving this IP into the CurrentScan table:192.168.1.177
08:11:13 [Process Scan] Print Stats
08:11:13 [Scan Stats] Devices Detected.......: 23
08:11:13 [Scan Stats] New Devices............: 0
08:11:13 [Scan Stats] Down Alerts............: 0
08:11:13 [Scan Stats] New Down Alerts........: 0
08:11:13 [Scan Stats] New Connections........: 8
08:11:13 [Scan Stats] Disconnections.........: 0
08:11:13 [Scan Stats] IP Changes.............: 0
08:11:13 [Scan Stats] Scan Method Statistics:
```

Please confirm you received repeated notification alerts during the time captured in these logs. If not, can you send me a section of the log file when new device notifications are being repeatedly sent? 

Thanks,
j

**Comment by rama31244** [comment]
Hi,
Yes i received a couple of email notifications that day. I have included a larger section of the log file below (had to zip it since it was 30mb). In this time period, I've received over 20 email notifications

Thanks again for your help
[pialert.log.zip](https://github.com/jokob-sk/Pi.Alert/files/12868294/pialert.log.zip)

**Comment by jokob-sk** [comment]
Thanks @rama31244 for the logs. I can see there are repeated notifications, but I can't seem to determine the root cause.  

I'll need more details to investigate this further.

1. Can you try to increase the time between schedules or disable the `DB cleanup` plugin to see if that makes a difference?
2. Do your devices have a static or [dynamic MAC](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/RANDOM_MAC.md) set for your network?
3. Do the following devices have something in common (e.g. firewall rules?)?
- `CoreELECdomain`, The device with the IP `192.168.1.128`, `yeelink-light-color1_miio57708366domain`
4. Are you running any backup software on the volume where you host the `pialert.db` file and could it interfere with the data consistency (if you are running backups, what interval are they scheduled for)? 

It seems like the DB is almost completely wiped at 11 am every day - can you post your docker compose file?

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/c90c9363-c9b0-4052-9378-4523485fa3c0)

**Comment by rama31244** [comment]
1. Can you try to increase the time between schedules or disable the DB cleanup plugin to see if that makes a difference?
I've disabled the DB cleanup so we'll see what happens tomorrow
2. Do your devices have a static or dynamic MAC?
Dynamic
3. Do the following devices have something in common (e.g. firewall rules?)?
    CoreELECdomain, The device with the IP 192.168.1.128, yeelink-light-color1_miio57708366domain
No they don't really. In fact I don't even have a device with IP 192.168.1.128 at the moment so I wonder whether the device has been reassigned to a new IP
 4. Are you running any backup software on the volume where you host the pialert.db file and could it interfere with the data consistency (if you are running backups, what interval are they scheduled for)? Yes I run backups of the appdata folders for all my docker containers on a weekly basis but I have done this for months with no problems
 5. It seems like the DB is almost completely wiped at 11 am every day - can you post your docker compose file?
I'm running pialert on Unraid so don't have a docker compose file. Is there something else I can provide instead?
 6. If you are using watchtower or similar, can you try to disable it?
 I'm running an autoupdate plugin for unraid on all my docker containers so have disabled this for Pialert and will see what happens tomorrow

Thanks again, i'll keep you up to date

**Comment by steved411** [comment]
I'm having the same issue. I had been running PiAlert under UnRaid for a while, and after upgrading to 23.10.2, I started to receive a ton of notification emails to "new devices," which weren't new. To rule out something with UnRaid, I deployed it on a Linux host via Docker. At first, everything seemed fine, then about 8 hours later, I started to get slammed with email notifications regarding new devices (pretty much every device was flagged as new). 

My latest deployment has no backups and nothing similar to watchtower. 

Here is my docker-compose file

`version: "3"
services:
  pialert:
    container_name: pialert
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/pi.alert_dev:latest"
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /otp/docker/pialert/config:/home/pi/pialert/config
      - /opt/docker/pialert/db:/home/pi/pialert/db
      # (optional) useful for debugging if you have issues setting up the container
      - /opt/docker/pialert/logs:/home/pi/pialert/front/log
    environment:
      - PORT=20211`

**Comment by jokob-sk** [comment]
Hi @steved411,

1. Can you please provide your pialert.conf and pialert.log files? 
2. Can you try to increase the time between schedules or disable the DB cleanup plugin to see if that makes a difference?

Thanks in advance,
j

**Comment by jokob-sk** [comment]
Hi @rama31244 ,

Can you please let us know if the issues have stopped?

If so, can you try to slowly enable each of the disabled settings/host setup to identify the root cause of the issue?

Thanks in advance,
j

**Comment by rama31244** [comment]
No. I've disabled the docker update application and the db cleanup but nothing has changed. I'm still receiving new device notifications

**Comment by jokob-sk** [comment]
Thank you for the reply - can you please send me the latest pialert.log file?

**Comment by rama31244** [comment]
[pialert.log.zip](https://github.com/jokob-sk/Pi.Alert/files/12899751/pialert.log.zip)
It's pretty big but here you go

**Comment by jokob-sk** [comment]
@rama31244 thanks a lot!

If that's the latest log file, then the issue might be your local time settings. Can you verify your local system time and date are set correctly? The latest timestamps in your log are around 2 days old:

`1697094187` - 12/10/2023, 6:03:07 pm (based on this website https://timestamp.online/)

> When any DB cleanup runs, it takes the current time, subtracts the days for the DB cleanup of events etc and compares it to the local time. That then clears events and to PiAlert it seems like there are no previous events, thus, new events of existing devices are reported as new devices. 

You saved the configuration on `12/10/2023, 6:03:07 pm`. After that time I can't seem to find duplicate notifications as all notifications contain devices with unique MAC addresses.

It seems like all notifications after you re-saved the config are legitimate, as all have different MAC addresses. PiAlert relies on the uniqueness of MAC addresses to determine if it is a new or existing device, please confirm you have read this documentation:

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/RANDOM_MAC.md

Here are the detected devices after `12/10/2023, 6:03:07 pm`:

```json

    "json": {
        "data": [
            {
                "MAC": "00:1e:06:42:b9:d0",
                "Datetime": "2023-10-12 18:55:14+11:00",
                "IP": "192.168.1.129",
                "Event Type": "New Device",
                "Device name": "CoreELECdomain",
                "Comments": ""
            },
            {
                "MAC": "ec:9c:32:59:07:67",
                "Datetime": "2023-10-12 18:55:14+11:00",
                "IP": "192.168.1.128",
                "Event Type": "New Device",
                "Device name": "(name not found)",
                "Comments": ""
            }
        ]
    }
```

```json
	
	
	"json": {
        "data": [
            {
                "MAC": "d0:3c:1f:54:d2:7e",
                "Datetime": "2023-10-12 19:30:53+11:00",
                "IP": "192.168.1.200",
                "Event Type": "New Device",
                "Device name": "LAPTOP-MJEO2NC3domain",
                "Comments": ""
            }
        ]
    }

```
```json
	
	{
        "data": [
            {
                "MAC": "34:ce:00:8e:9b:9b",
                "Datetime": "2023-10-12 23:00:50+11:00",
                "IP": "192.168.1.133",
                "Event Type": "New Device",
                "Device name": "yeelink-light-color1_miio57708366domain",
                "Comments": ""
            }
        ]
    }
```
```json
	
	{
        "data": [
            {
                "MAC": "3c:5c:c4:92:09:0c",
                "Datetime": "2023-10-12 23:06:00+11:00",
                "IP": "192.168.1.132",
                "Event Type": "New Device",
                "Device name": "(name not found)",
                "Comments": ""
            }
        ]
    }
	
```
```json
	{
        "data": [
            {
                "MAC": "00:e0:4c:68:0d:58",
                "Datetime": "2023-10-14 07:35:22+11:00",
                "IP": "192.168.1.121",
                "Event Type": "New Device",
                "Device name": "MacBook-Prodomain",
                "Comments": ""
            }
        ]
    }
```

```

**Comment by jokob-sk** [comment]
Wait a bit - I might have been able to reproduce the behavior on my end - I will keep you posted.

**Comment by rama31244** [comment]
Really sorry for the stupid questions but how can I verify the time and day
being set correctly? The unraid server definitely has the correct time and
date but do I need to check specifically for the pialert container?

**Comment by jokob-sk** [comment]
Okay - still can't reproduce it on my end. I've implemented additional logging if a new device notification is sent out to print out the whole CurrentScan and Devices tables.

Can you try:

1. Purge the log file
2. Backup everything
3. Change the docker image to the dev one (`pi.alert_dev`)
4. Rebuild the container
5. Observe and if the issue happens again, please send me the pialeret.log file for further investigation.
6. Make sure your TIMEZONE setting in PiAlert is set correctly and aligns with your unraid system. 

⚠Please note some things are under development in the dev image, so things might not work. Make sure you enable the new SMTP plugin to receive email notifications. ⚠

**Comment by rama31244** [comment]
I've installed the dev version but now when I got to pruge log files or
save the settings it says 'unable to open file'. Is that a permissions
issue?

**Comment by jokob-sk** [comment]
Possibly - can you post a screenshot?

**Comment by jokob-sk** [comment]
Thanks for the update and help 👍
Just make sure you enable `DB cleanup` at least once a week or so at least. Let me know if the issues re-surface.
I'll keep working on resolving the remaining issues on the `_dev` image.

**Comment by jhonderson** [comment]
This is happening to me after installing this fork of Pi.alert for the first time (latest docker tag). Would you recommend moving to the previous version in the meantime? (I had to export the devices information to CSV cuz it was being reset every time)

**Comment by jokob-sk** [comment]
if you can please test the _dev image to see if issues persist @jhonderson

**Comment by jhonderson** [comment]
Hello @jokob-sk ,

I confirm I am still having this issue with the _dev image.

After checking the logs I noticed the issue happened only after the plugin [db_cleanup](https://github.com/jokob-sk/Pi.Alert/tree/main/front/plugins/db_cleanup) was executed. So I entered the docker container and execute it manually to see its output:
```bash
docker exec -it pialert bash
source /myenv/bin/activate
/home/pi/pialert/front/plugins/db_cleanup/script.py pluginskeephistory=250 hourstokeepnewdevice=0 daystokeepevents=90 pholuskeepdays=30

[plugin_helper] reading config file
11:12:02 [DBCLNP] In script
11:12:02 [DBCLNP] Upkeep Database:
11:12:02 [DBCLNP] Online_History: Delete all but keep latest 150 entries
11:12:02 [DBCLNP] Optimize Database
11:12:02 [DBCLNP] Events: Delete all older than 90 days (DAYS_TO_KEEP_EVENTS setting)
11:12:02 [DBCLNP] Plugins_History: Trim Plugins_History entries to less than 250 per Plugin (PLUGINS_KEEP_HIST setting)
11:12:02 [DBCLNP] Plugins_History: Trim Notifications entries to less than 100
11:12:02 [DBCLNP] Pholus_Scan: Delete all older than 30 days (PHOLUS_DAYS_DATA setting)
11:12:02 [DBCLNP] Devices: Delete all New Devices older than 0 hours (HRS_TO_KEEP_NEWDEV setting)
11:12:02 [DBCLNP] Plugins_Objects: Delete all duplicates
11:12:02 [DBCLNP] Pholus_Scan: Delete all duplicates
11:12:02 [DBCLNP] Shrink Database
11:12:02 [DBCLNP] Cleanup complete file 
```

Then I observed that the **devices deletion statement** is being executed even though the parameter `hourstokeepnewdevice` has value `0`. After looking at the code, I believe the problem is in [this line](https://github.com/jokob-sk/Pi.Alert/blob/main/front/plugins/db_cleanup/script.py#L123):
```python
if HRS_TO_KEEP_NEWDEV != 0:
```

The code is assuming the variable `HRS_TO_KEEP_NEWDEV` is a number, but it is actually a string, which is causing the condition to always be true.

Let me know if this makes sense to you.

**Comment by jokob-sk** [comment]
Thank you for the debugging and fix @jhonderson - much appreciated 🙏

**Comment by jokob-sk** [comment]
Released in 23.11.11
